_format_version: "3.0"
_transform: true

plugins:
  - name: ai-rate-limiting-advanced
    consumer: free
    config:
      llm_providers:
        - name: openai
          limit:
            - 100
          window_size:
            - 60
      strategy: redis
      sync_rate: 0
      redis:
        host: redis
        port: 6379
  - name: ai-rate-limiting-advanced
    consumer: paid
    config:
      llm_providers:
        - name: openai
          limit:
            - 4000
          window_size:
            - 60
      strategy: redis
      sync_rate: 0
      redis:
        host: redis
        port: 6379
