{
 "title": "Kong - CX AI",
 "description": "Dashboard that graphs metrics exported via Prometheus plugin in Kong (http://github.com/kong/kong)\r\n+ Total Requests",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values({__name__=~\"kong_http_requests_total|kong_kong_latency_ms_bucket\"},service)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kong_nginx_connections_total,instance)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values({__name__=~\"kong_http_requests_total|kong_kong_latency_ms_bucket\"},route)"
    }
   },
   {
    "name": "upstream",
    "query": {
     "query": "label_values(kong_upstream_target_health, upstream)"
    }
   },
   {
    "name": "ai_provider",
    "query": {
     "query": "label_values({__name__=~\"kong_ai_cost_total|kong_ai_requests_total|kong_ai_cache_store_latency_ms_sum|kong_ai_cache_retrieve_latency_ms_sum\"},ai_provider)"
    }
   },
   {
    "name": "cache",
    "query": {
     "query": "label_values({__name__=~\"kong_ai_requests_total|kong_ai_cost_total\"},cache)"
    }
   },
   {
    "name": "ai_model",
    "query": {
     "query": "label_values({__name__=~\"kong_ai_cost_total|kong_ai_requests_total|kong_ai_cache_store_latency_ms_sum|kong_ai_cache_retrieve_latency_ms_sum\"},ai_model)"
    }
   },
   {
    "name": "db_name",
    "query": {
     "query": "label_values({__name__=~\"kong_ai_cache_retrieve_latency_ms_bucket|kong_ai_cache_store_latency_ms_bucket\"},db_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "AI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AI Total Request",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kong_ai_requests_total)", "legendFormat": "Total" },
    {
     "expr": "sum by(ai_provider) (kong_ai_requests_total{cache=~\"$cache\", ai_provider=~\"$ai_provider\", ai_model=~\"$ai_model\"})",
     "legendFormat": "{{ai_provider}}"
    }
   ]
  },
  {
   "title": "Tokens comsumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(token_type) (kong_ai_tokens_total{ai_provider=~\"$ai_provider\", ai_model=~\"$ai_model\", cache=~\"$cache\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost AI Request",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cache) (kong_ai_cost_total{ai_provider=~\"$ai_provider\", ai_model=~\"$ai_model\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Vector",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(db_name) (kong_ai_requests_total{db_name!=\"\", ai_provider=~\"$ai_provider\", ai_model=~\"$ai_model\"})",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "AI Requests Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by (ai_provider)(kong_ai_requests_total{cache=~\"$cache\", ai_provider=~\"$ai_provider\", ai_model=~\"$ai_model\"})",
     "legendFormat": "{{ai_provider}}"
    }
   ]
  },
  {
   "title": "AI Retrieve Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_cache_retrieve_latency_ms_bucket{ai_provider=~\"$ai_provider\", db_name=~\"$db_name\"}[1m])) by (le,db_name))",
     "legendFormat": "p90-{{db_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_cache_retrieve_latency_ms_bucket{ai_provider=~\"$ai_provider\", ai_model=~\"$ai_model\"}[1m])) by (le,db_name))",
     "legendFormat": "p95-{{db_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_cache_retrieve_latency_ms_bucket{ai_provider=~\"$ai_provider\", ai_model=~\"$ai_model\"}[1m])) by (le,db_name))",
     "legendFormat": "p99-{{db_name}}"
    }
   ]
  },
  {
   "title": "AI Store Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_cache_store_latency_ms_bucket{ai_provider=~\"$ai_provider\", db_name=~\"$db_name\"}[1m])) by (le,db_name))",
     "legendFormat": "p90-{{db_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_cache_store_latency_ms_bucket{ai_provider=~\"$ai_provider\", db_name=~\"$db_name\"}[1m])) by (le,db_name))",
     "legendFormat": "p95-{{db_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_cache_store_latency_ms_bucket{ai_provider=~\"$ai_provider\", db_name=~\"$db_name\"}[1m])) by (le,db_name))",
     "legendFormat": "p99-{{db_name}}"
    }
   ]
  },
  {
   "title": "Caching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Kong shared memory usage by Node ($instance)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(kong_memory_lua_shared_dict_bytes{instance=~\"$instance\",shared_dict!~\"kong_process_events\"}/kong_memory_lua_shared_dict_total_bytes{instance=~\"$instance\",shared_dict!~\"kong_process_events\"})*100",
       "legendFormat": "{{shared_dict}} ({{kong_subsystem}})"
      }
     ]
    },
    {
     "title": "Kong worker Lua VM usage by Node ($instance)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
     "repeat": "instance",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kong_memory_workers_lua_vms_bytes{instance=~\"$instance\"}",
       "legendFormat": "PID:{{pid}} ({{kong_subsystem}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Nginx connection state",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kong_nginx_connections_total{state=~\"active|reading|writing|waiting\", instance=~\"$instance\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Total Connections",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kong_nginx_connections_total{state=\"total\", instance=~\"$instance\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Handled Connections",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kong_nginx_connections_total{state=\"handled\", instance=~\"$instance\"})",
       "legendFormat": "Handled"
      }
     ]
    },
    {
     "title": "Accepted Connections",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kong_nginx_connections_total{state=\"accepted\", instance=~\"$instance\"})",
       "legendFormat": "Accepted"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(last_over_time(kong_http_requests_total{instance=~\"$instance\"}[30d]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Total requests per second (RPS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Requests/second"
    }
   ]
  },
  {
   "title": "RPS per route/service ($service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "RPS per route/service by status code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (service,code)",
     "legendFormat": "service:{{service}}-{{code}}"
    },
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (route,code)",
     "legendFormat": "route:{{route}}-{{code}}"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kong Proxy Latency across all services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Kong Proxy Latency per Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p90-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p95-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p99-{{service}}"
    }
   ]
  },
  {
   "title": "Kong Proxy Latency per Route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p90-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p95-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p99-{{route}}"
    }
   ]
  },
  {
   "title": "Request Time across all services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Request Time per service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p90-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p95-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p99-{{service}}"
    }
   ]
  },
  {
   "title": "Request Time per Route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p90-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p95-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p99-{{route}}"
    }
   ]
  },
  {
   "title": "Upstream time across all services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Upstream Time across per service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p90-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p95-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
     "legendFormat": "p99-{{service}}"
    }
   ]
  },
  {
   "title": "Upstream Time across per Route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p90-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p95-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "p99-{{route}}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{instance=~\"$instance\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Egress per service/route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{direction=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(irate(kong_bandwidth_bytes{direction=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "Ingress per service/route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{direction=\"ingress\", service =~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Healthy status",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "sum(kong_upstream_target_health{state=\"healthy\",upstream=~\"$upstream\"}) by (upstream,target,address) * -1  + sum(kong_upstream_target_health{state=~\"(unhealthy|dns_error)\",upstream=~\"$upstream\"}) by (upstream,target,address)",
     "legendFormat": "{{upstream}}:{{target}}::{{address}}"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "sum(\n# map state to a numeric value\n# since grafana doesn't support value mapping yet\n  label_replace(\n    label_replace(\n      label_replace(\n       kong_upstream_target_health{upstream=~\"$upstream\"}\n       # healthy is positive number\n       , \"state_value\", \"1\", \"state\", \"healthy\"\n       # healthchecks_off is 0\n      ), \"state_value\", \"0\", \"state\", \"healthchecks_off\"\n      # unhealthy is negative number\n    ), \"state_value\", \"-1\", \"state\", \"(dns_error|unhealthy)\"\n  )\n)\nby (upstream, target, address, state, state_value) > 0"
    }
   ]
  }
 ]
}