{
 "title": "Kong AI Gateway Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kong_nginx_connections_total,instance)"
    }
   },
   {
    "name": "ai_provider",
    "query": {
     "query": "label_values(kong_ai_llm_requests_total,ai_provider)"
    }
   },
   {
    "name": "ai_model",
    "query": {
     "query": "label_values(kong_ai_llm_requests_total,ai_model)"
    }
   },
   {
    "name": "embeddings_provider",
    "query": {
     "query": "label_values(kong_ai_llm_requests_total,embeddings_provider)"
    }
   },
   {
    "name": "embeddings_model",
    "query": {
     "query": "label_values(kong_ai_llm_requests_total,embeddings_model)"
    }
   },
   {
    "name": "consumer",
    "query": {
     "query": "label_values(kong_ai_llm_requests_total,consumer)"
    }
   },
   {
    "name": "token_type",
    "query": {
     "query": "label_values(kong_ai_llm_tokens_total,token_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Request rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests per second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(kong_ai_llm_requests_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS per AI Provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(kong_ai_llm_requests_total{ instance=~\"$instance\", ai_provider=~\"$ai_provider\"}[1m]))",
     "legendFormat": "$ai_provider"
    }
   ]
  },
  {
   "title": "RPS per AI Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(kong_ai_llm_requests_total{instance=~\"$instance\", ai_model=~\"$ai_model\"}[1m]))",
     "legendFormat": "$ai_model"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "LLM Provider Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "LLM Provider Latency per AI Provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\", ai_provider=\"$ai_provider\"}[1m])) by (le))",
     "legendFormat": "P90-$ai_provider"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\", ai_provider=\"$ai_provider\"}[1m])) by (le))",
     "legendFormat": "P95-$ai_provider"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\", ai_provider=\"$ai_provider\"}[1m])) by (le))",
     "legendFormat": "P99-$ai_provider"
    }
   ]
  },
  {
   "title": "LLM Provider Latency per AI Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\", ai_model=\"$ai_model\"}[1m])) by (le))",
     "legendFormat": "P90-$ai_model"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\", ai_model=\"$ai_model\"}[1m])) by (le))",
     "legendFormat": "P95-$ai_model"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_llm_provider_latency_ms_bucket{instance=~\"$instance\", ai_model=\"$ai_model\"}[1m])) by (le))",
     "legendFormat": "P99-$ai_model"
    }
   ]
  },
  {
   "title": "AI Cache Fetch Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\"}[1m]))by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "AI Cache Fetch Latency per AI Provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\", ai_provider=\"$ai_provider\"}[1m])) by (le))",
     "legendFormat": "P90-$ai_provider"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\", ai_provider=\"$ai_provider\"}[1m])) by (le))",
     "legendFormat": "P95-$ai_provider"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\", ai_provider=\"$ai_provider\"}[1m])) by (le))",
     "legendFormat": "P99-$ai_provider"
    }
   ]
  },
  {
   "title": "AI Cache Fetch Latency per AI Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\", ai_model=\"$ai_model\"}[1m])) by (le))",
     "legendFormat": "P90-$ai_model"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\", ai_model=\"$ai_model\"}[1m])) by (le))",
     "legendFormat": "P95-$ai_model"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_cache_fetch_latency_ms_bucket{instance=~\"$instance\", ai_model=\"$ai_model\"}[1m])) by (le))",
     "legendFormat": "P99-$ai_model"
    }
   ]
  },
  {
   "title": "AI Cache Embedding Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "AI Cache Embedding Latency per Embeddings Provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_provider=\"$embeddings_provider\"}[1m])) by (le))",
     "legendFormat": "P90-$embeddings_provider"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_provider=\"$embeddings_provider\"}[1m])) by (le))",
     "legendFormat": "P95-$embeddings_provider"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_provider=\"$embeddings_provider\"}[1m])) by (le))",
     "legendFormat": "P99-$embeddings_provider"
    }
   ]
  },
  {
   "title": "AI Cache Embedding Latency per AI Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_model=~\"$embeddings_model\"}[1m])) by (le))",
     "legendFormat": "P90-$embeddings_model"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_model=~\"$embeddings_model\"}[1m])) by (le))",
     "legendFormat": "P95-$embeddings_model"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_cache_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_model=~\"$embeddings_model\"}[1m])) by (le))",
     "legendFormat": "P99-$embeddings_model"
    }
   ]
  },
  {
   "title": "AI RAG Fetch Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\"}[1m]))by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "AI RAG Fetch Latency per AI Provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\", ai_provider=\"$ai_provider\"}[1m])) by (le))",
     "legendFormat": "P90-$ai_provider"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\", ai_provider=\"$ai_provider\"}[1m])) by (le))",
     "legendFormat": "P95-$ai_provider"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\", ai_provider=\"$ai_provider\"}[1m])) by (le))",
     "legendFormat": "P99-$ai_provider"
    }
   ]
  },
  {
   "title": "AI RAG Fetch Latency per AI Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\", ai_model=\"$ai_model\"}[1m])) by (le))",
     "legendFormat": "P90-$ai_model"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\", ai_model=\"$ai_model\"}[1m])) by (le))",
     "legendFormat": "P95-$ai_model"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_rag_fetch_latency_ms_bucket{instance=~\"$instance\", ai_model=\"$ai_model\"}[1m])) by (le))",
     "legendFormat": "P99-$ai_model"
    }
   ]
  },
  {
   "title": "AI RAG Embedding Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "AI RAG Embedding Latency per AI Provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\", ai_provider=\"$ai_provider\"}[1m])) by (le))",
     "legendFormat": "P90-$ai_provider"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\", ai_provider=\"$ai_provider\"}[1m])) by (le))",
     "legendFormat": "P95-$ai_provider"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\", ai_provider=\"$ai_provider\"}[1m])) by (le))",
     "legendFormat": "P99-$ai_provider"
    }
   ]
  },
  {
   "title": "AI RAG Embedding Latency per AI Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_model=\"$embeddings_model\"}[1m])) by (le))",
     "legendFormat": "P90-$embeddings_model"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_model=\"$embeddings_model\"}[1m])) by (le))",
     "legendFormat": "P95-$embeddings_model"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_ai_rag_embeddings_latency_ms_bucket{instance=~\"$instance\", embeddings_model=\"$embeddings_model\"}[1m])) by (le))",
     "legendFormat": "P99-$embeddings_model"
    }
   ]
  },
  { "title": "Costs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Cost Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(kong_ai_llm_cost_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost Total per Consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "kong_ai_llm_cost_total{instance=~\"$instance\", ai_provider=~\"$ai_provider\", ai_model=~\"$ai_model\", embeddings_model=\"\"}",
     "legendFormat": "{{consumer}}"
    }
   ]
  },
  { "title": "Tokens", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Token Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum(kong_ai_llm_tokens_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token Total per AI Provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "sum(kong_ai_llm_tokens_total{instance=~\"$instance\", ai_provider=~\"$ai_provider\"})",
     "legendFormat": "$ai_provider"
    }
   ]
  },
  {
   "title": "Token Total per AI Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 76 },
   "targets": [
    {
     "expr": "sum(kong_ai_llm_tokens_total{instance=~\"$instance\", ai_model=~\"$ai_model\"})",
     "legendFormat": "$ai_model"
    }
   ]
  },
  {
   "title": "Token Total per Token Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "sum(kong_ai_llm_tokens_total{instance=~\"$instance\", token_type=~\"$token_type\"}) by (token_type)",
     "legendFormat": "{{token_type}}"
    }
   ]
  },
  {
   "title": "Token Total per Consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "sum(kong_ai_llm_tokens_total{instance=~\"$instance\", consumer=~\"$consumer\"}) by (consumer)",
     "legendFormat": "{{consumer}}"
    }
   ]
  }
 ]
}